from typing import Any, Iterator, MutableMapping, TypeVar


Key = TypeVar('Key')
Value = TypeVar('Value')

class Cache(MutableMapping[Key, Value]):

    def __init__(self, maxsize: int): ...
    def __getitem__(self, key: Key) -> Value: ...
    def __setitem__(self, key: Key, value: Value): ...
    def __delitem__(self, key: Key): ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...

class TTLCache(Cache[Key, Value]):

    def __init__(self, maxsize: int, ttl: int): ...
