from typing import Optional, Type

from .cursors import Cursor

class Connection:
    def close(self) -> None: ...
    def commit(self): ...
    def cursor(self, cursor: Optional[Type[Cursor]] = ...) -> Cursor: ...
