from typing import Optional

from .cursors import Cursor

class Connection:
    def close(self) -> None: ...
    def commit(self) -> None: ...
    def cursor(self, cursor: Optional[type[Cursor]] = ...) -> Cursor: ...
