name: Test
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: '3.11'
            job-number: 1
          # the job number is included in the page title;
          # only pages for job numbers 1 and 2 have been set up so far,
          # so if you add a third job, you must manually create the extra pages first
          # (the bot password does not have permission to create pages) –
          # see test_runner.py (note that it uses two test wikis!)
    services:
      mariadb:
        image: mariadb:10.1
        env:
          MYSQL_ROOT_PASSWORD: 'mariadb-root-password'
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: make check
        env:
          MARIADB_ROOT_PASSWORD: 'mariadb-root-password'
          MARIADB_PORT: ${{ job.services.mariadb.ports['3306'] }}
          MW_USERNAME: ${{ secrets.MW_USERNAME }}
          MW_PASSWORD: ${{ secrets.MW_PASSWORD }}
          CI_JOB_NUMBER: ${{ matrix.job-number }}
